#
# GitHub - Workflow syntax for GitHub Actions https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Deploy to Cloud Run from Source

on:
  push:
    paths: 
      - 'gqlgen/**'
      - '.github/workflows/github-actions-demo.yml'
    branches: [main]

env:
  PROJECT_ID: richard-experiment # TODO: update Google Cloud project id
  GAR_LOCATION: ap-northeast1 # TODO: update Artifact Registry location
  REPOSITORY: reponame-ghact # TODO: update Artifact Registry repository name
  SERVICE: gqlgen-server # TODO: update Cloud Run service name
  REGION: ap-northeast1 # TODO: update Cloud Run service region
  
  
jobs:
  deploy:
    environment: dev
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: "read"
      id-token: "write" # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings

    runs-on: ubuntu-latest
    steps:
      # actions/checkout MUST come before "google-github-actions/auth" https://github.com/google-github-actions/auth
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          token_format: 'access_token'
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}" # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}" # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v2'
        with:
          username: 'oauth2accesstoken'
          # password: '${{ secrets.PASSWORD }}'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          
          
      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./gqlgen
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          
